apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-mdt
  labels:
    prometheus: prometheus-mdt
spec:
  replicas: 2
  serviceAccountName: prometheus-operator-mdt
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yml
