dashboard_namespace: custom-dashboards
prometheus_scrape_config:
  - job_name: "federated-local-prometheus"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="openshift-state-metrics"}'
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
          - "prometheus-k8s-openshift-monitoring.apps.cluster-9c34.sandbox302.opentlc.com"

openshift_cluster_content:
  - object: Dashboards - DevOps
    content:
      - name: Software Delivery Metrics Dashboard
        file: "{{ inventory_dir }}/../dashboard-sdm.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: Mount Software Delivery Dashboard to Grafana
        action: patch
        file: "{{ inventory_dir }}/../grafana-deployment.yml"
        params: "{{ inventory_dir }}/../sdm-volume-patch.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
  - object: Uber Prometheus
    content:
      - name: Monitored prometheus perms
        file: "{{ inventory_dir }}/../k8s_prometheus.yml"
        namespace: openshift-monitoring
        tags:
          - dashboard-sdm
      - name: Prometheus operator
        file: "{{ inventory_dir }}/../prometheus-operator-config.yml.j2"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: Scrape config secret
        file: "{{ inventory_dir }}/../prometheus-scrape-config-secret.yml.j2"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: Prometheus CR
        file: "{{ inventory_dir }}/../prometheus-cr.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: Prometheus Service
        file: "{{ inventory_dir }}/../prometheus-svc.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: Prometheus Route
        file: "{{ inventory_dir }}/../prometheus-route.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
