dashboard_namespace: custom-dashboards
prometheus_scrape_config:
  - job_name: "federated-prometheus-1"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="openshift-state-metrics"}'
    scheme: "https"
    basic_auth:
      username: 'internal'
      password: 'CumopVL1TG926oC12xaLRlXQ7/oiLOm02aDc2olxAQp8ZdX1BBWMfanxJrtTS/yADrd7zBDf28gLQkS6gtGZ79SRNqYCK+aHgOYwKiy0CBxvE9ImdC27u3bziQWZVa0fFi9GukV+HGbVAy6BYw3P4y+LD+2NfXanRIfnu/8vmFdOOW6sypc8/ZLPZjGFQ8B+PvkOicH5e+U90QTlOZSIjYrumq8KSXPRr8DPXsURzNF3BQRCULvDWhN39nqWFW1xXCUL9woAYY2G9QdLFqDhHXYzgAk8clxj4pK47LoNAjjWF87SHGzmnEqCV53G2+WChCV7NbiAVubWGt1exhvI'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
        labels:
          federated_job: "federated-prometheus-1"
  - job_name: "federated-prometheus-2"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="openshift-state-metrics"}'
    scheme: "https"
    basic_auth:
      username: 'internal'
      password: 'pxn+CuOVU7ZFIoB3fAzuuDxIUouzrCThcZ2xqYljmdlwEms09jnWI0kIO2xAEnLKnTvPst08V/M60uxYiNGBV7/ocljsPnAdMpURHYPeOvY4lPDeh4wJSE08ccD7VvWJhs22bhM1zBX4dEy9RaIL647G1QumpKQZ2roGwdfbbD92ghLnwEN5NmODWTv33Jgc4MpRv208ZAIiQ2dj9bjtzPcR4x9hSmwgI0BBiJtZSYuvCnaB+c3u15svwzAsP48rDGBeOlEOPUKU0mg/BRAg5RqWMREKH/mwIEc+X7xWVa4Rv4eydtmXkFvUj1qCNBKBgSNur5MHR6H1AhwLTCfA'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "prometheus-k8s-openshift-monitoring.apps.ci-1.cop.rht-labs.com"
        labels:
          federated_job: "federated-prometheus-2"

openshift_cluster_content:
  - galaxy_requirements: 
      - "{{ inventory_dir }}/../mdt-secret-discovery-requirements.yml"
  - object: MDT Prometheus
    pre_steps:
      - role: mdt-quickstart/secret-discovery
    content:
      - name: MDT Prometheus htpasswd secret
        file: "{{ inventory_dir }}/../prometheus-htpasswd-secret.yml.j2"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: MDT Prometheus operator
        file: "{{ inventory_dir }}/../prometheus-operator-config.yml.j2"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: MDT Scrape config secret
        file: "{{ inventory_dir }}/../prometheus-scrape-config-secret.yml.j2"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: MDT Prometheus CR
        file: "{{ inventory_dir }}/../prometheus-cr.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: MDT Prometheus Service
        file: "{{ inventory_dir }}/../prometheus-svc.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: MDT Prometheus Route
        file: "{{ inventory_dir }}/../prometheus-route.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: MDT Prometheus Oauth Cluster Role
        file: "{{ inventory_dir}}/../prometheus-oauth-cluster-role.yml"
        tags:
          - dashboard-sdm
      - name: MDT Prometheus Oauth Service Account
        file: "{{ inventory_dir }}/../prometheus-sa.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard sdm
      - name: MDT Prometheus Oauth ClusterRoleBinding
        file: "{{ inventory_dir }}/../prometheus-oauth-cluster-role-binding.yml.j2"
        tags:
          - dashboard-sdm
      - name: MDT Repoint Grafana Datasource
        file: "{{ inventory_dir }}/../grafana-mdt-datasources.yml.j2"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
  - object: Dashboards - DevOps
    content:
      - name: Software Delivery Metrics Dashboard
        file: "{{ inventory_dir }}/../dashboard-sdm.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
      - name: Mount Software Delivery Dashboard to Grafana
        action: patch
        file: "{{ inventory_dir }}/../grafana-deployment.yml"
        params: "{{ inventory_dir }}/../sdm-volume-patch.yml"
        namespace: "{{ dashboard_namespace }}"
        tags:
          - dashboard-sdm
