---
- name: Fetch k8s prometheus htpasswd config
  k8s_facts:
    api_version: v1
    kind: Secret
    namespace: openshift-monitoring
    name: prometheus-k8s-htpasswd
  register: prometheus_k8s_htpasswd_data

- name: Set mdt prometheus htpasswd secret fact
  set_fact: 
    mdt_prometheus_htpasswd_auth: "{{ prometheus_k8s_htpasswd_data.resources[0]['data']['auth'] }}"

- name: Fetch monitoring grafana datasources configuration
  k8s_facts:
    api_version: v1
    kind: Secret
    namespace: openshift-monitoring
    name: grafana-datasources
  register: grafana_datasources_data

- name: Decode grafana datasources data
  set_fact:
    grafana_datasources_with_mdt_prometheus_encoded: "{{ grafana_datasources_data.resources[0]['data']['prometheus.yaml'] }}"

- name: Print variables
  debug:
    msg: >-
      Data: {{ grafana_datasources_with_mdt_prometheus_encoded }}
    verbosity: 2
