---
- name: Fetch k8s prometheus htpasswd config
  k8s_facts:
    api_version: v1
    kind: Secret
    namespace: openshift-monitoring
    name: prometheus-k8s-htpasswd
  register: prometheus_k8s_htpasswd_data

- name: Set mdt prometheus htpasswd secret fact
  set_fact: 
    mdt_prometheus_htpasswd_auth: "{{ prometheus_k8s_htpasswd_data.resources[0]['data']['auth'] }}"

- name: Fetch monitoring grafana datasources configuration
  k8s_facts:
    api_version: v1
    kind: Secret
    namespace: openshift-monitoring
    name: grafana-datasources
  register: grafana_datasources_data

- name: Decode grafana datasources data
  set_fact:
    orig_grafana_datasources_with_prometheus: "{{ grafana_datasources_data.resources[0]['data']['prometheus.yaml'] | b64decode }}"

- name: Setup new grafana datasources config
  set_fact:
    new_grafana_datasources_mdt_data_yaml:
      apiVersion: 1
      datasources:
        - access: "proxy"
          basicAuth: true
          basicAuthPassword: "{{ orig_grafana_datasources_with_prometheus['datasources'][0]['basicAuthPassword'] }}"
          basicAuthUser: "internal"
          editable: false
          jsonData:
            tlsSkipVerify: true
          name: "prometheus"
          orgId: 1
          type: "prometheus"
          url: "https://prometheus-mdt.{{ dashboard_namespace }}.svc:9091"
          version: 1

- name: Setup new grafana datasources config encoded
  set_fact:
    new_grafana_datasources_mdt_data: "{{ new_grafana_datasources_mdt_data_yaml | to_nice_json | b64encode }}"

- name: Print variables
  debug:
    msg: >-
      Data: "{{ new_grafana_datasources_mdt_data }}"
    verbosity: 2
