---
- name: Fetch k8s prometheus htpasswd config
  k8s_facts:
    api_version: v1
    kind: Secret
    namespace: openshift-monitoring
    name: prometheus-k8s-htpasswd
  register: prometheus_k8s_htpasswd_data

- name: Set mdt prometheus htpasswd secret fact
  set_fact: 
    mdt_prometheus_htpasswd_auth: "{{ prometheus_k8s_htpasswd_data.resources[0]['data']['auth'] }}"

- name: Print variables
  debug:
    msg: >-
      {{ mdt_prometheus_htpasswd_auth }}
    verbosity: 2
